services:
  - type: web
    name: shieldshare
    env: python
    buildCommand: pip install -r requirements.txt && python "File Sharing/database.py"
    startCommand: gunicorn --chdir "File Sharing" app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
